server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/trading_auth
    username: trading_user
    password: trading_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: yourSecretKey12345678901234567890123456789012
  expiration: 86400000 # 24 hours

logging:
  level:
    com.trading: DEBUG
    org.springframework.security: DEBUG
